### ISSUE TITLE
There is no documentation or introduction as to what this ApiClient actually do!

### ISSUE THREAD

**Issue by ahmadalibaloch** [FabianTerhorst/ApiClient#10]
Why are you combining retrofit and webapi with realm. Does this serve data from realm when offline and from webapi when online?

**Comment by FabianTerhorst** [comment]
Is instantly loading the data from realm while refreshing the data with retrofit. The refreshed data will saved and will update the observable.

**Comment by ahmadalibaloch** [comment]
Still confusing, and the purpose of this issue was to add introduction in the Readme file.

I can easily load data from server using retrofit and save into a realm database. Why are you combining both? We don't know about this library so elaborate a little what is the problem this library solves?

Do you have an accompanying article on Medium etc?

**Comment by FabianTerhorst** [comment]
I just moved some classes out of an internal project and created an library out of this.
