### ISSUE TITLE
App Crashes when App Launch without Internet

### ISSUE THREAD

**Issue by gupta-shubham93** [FabianTerhorst/ApiClient#11]
I first opened the app with internet connection and then again launched without internet.
The Log I received is written below:

*01-28 03:02:40.534 2226-2226/io.fabianterhorst.apiclient.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: io.fabianterhorst.apiclient.app, PID: 2226*

Could you please help me out with offline Integration as well? I really loved this integration

**Comment by FabianTerhorst** [comment]
You just have to catch the error with rxjava. 
```java
 .subscribe(
    System.out::println,
    error -> System.out.println("Error!")
  );
```

**Comment by gupta-shubham93** [comment]
Thank You for your help!
Still new to Rx Android.
