### ISSUE TITLE
saving, loading objects

### ISSUE THREAD

**Issue by Scit** [FabianTerhorst/ApiClient#3]
"The library is handling the saving, the loading and the refreshing for you." (c)
1. How should I save my model objects using this client? For example: I've fetched data from backend, then load it into UI, after that modify it. What should I do next?
2. What about caching? How can I load my data from cache after e.g. screen rotating; but fetch it from a server on "refresh" button?

Does ApiClient provide any API for this cases? Readme describes only fetching operations.
Anyway, thank you for the project!

**Comment by FabianTerhorst** [comment]
Apiclient is using Realm under the hood. Realm is saving every object change automatically GitHub.com/Realm/realm-java
