### ISSUE TITLE
io.fabianterhorst:apiclient-accountmanager:0.1 problem

### ISSUE THREAD

**Issue by Scit** [FabianTerhorst/ApiClient#4]
Gradle fails to resolve the dependency: "Error:(55, 13) Failed to resolve: io.fabianterhorst:apiclient-accountmanager:0.1"

I've added: 

```
    compile 'io.fabianterhorst:apiclient:0.3'
    compile 'io.fabianterhorst:apiclient-components:0.1'
    compile 'io.fabianterhorst:apiclient-accountmanager:0.1'
```

into my app's build.gradle but it doesn't work.

**Comment by FabianTerhorst** [comment]
The account Manager is not uploaded to jcenter. The account Manager is not needed for the apiclient to work.

**Comment by tallaltasawar** [comment]
Do i still need to add Retrofit, Realm, Gson, Rxjava and Retrolambda explicitly ? Because I have added these and got these errors. 

Error:(29, 13) Failed to resolve: io.fabianterhorst:apiclient:0.4

**Comment by FabianTerhorst** [comment]
version 0.4 isn´t published on jcenter

**Comment by tallaltasawar** [comment]
so I cant use it ? I really like the solution you have developed and am struggling withe the same problem, I need to use all these together (Retrofit, Realm, Gson, Rxjava and Retrolambda). any suggestions would be highly appreciated.
